apiVersion: batch/v1
kind: CronJob
metadata:
  name: fox-auditoria-sync
  namespace: fox-auditoria
  labels:
    app: fox-auditoria
    component: sync-job
spec:
  # Executar a cada 5 minutos
  schedule: "*/5 * * * *"
  
  # Configurações do CronJob
  concurrencyPolicy: Forbid  # Não permitir execuções simultâneas
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300  # 5 minutos para iniciar
  
  jobTemplate:
    spec:
      # Configurações do Job
      backoffLimit: 2  # Máximo 2 tentativas
      activeDeadlineSeconds: 240  # Timeout de 4 minutos
      
      template:
        metadata:
          labels:
            app: fox-auditoria
            component: sync-job
        spec:
          restartPolicy: Never
          
          containers:
          - name: fox-auditoria-sync
            image: python:3.11-slim
            imagePullPolicy: IfNotPresent
            
            # Comando para executar sincronização
            command: ["/bin/bash"]
            args:
              - -c
              - |
                echo "🚀 Iniciando sincronização FOX Auditoria..."
                echo "⏰ $(date): Job iniciado"
                
                # Instalar dependências como root
                echo "📦 Instalando dependências..."
                pip install --quiet --no-cache-dir pymongo==4.6.0 pandas==2.1.4 plotly==5.17.0
                
                # Executar script de sincronização
                echo "🔄 Executando sincronização..."
                python3 /app/sync_job.py
                
                echo "✅ $(date): Job concluído"
            
            # Variáveis de ambiente
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri
            - name: PYTHONPATH
              value: "/app"
            - name: PYTHONUNBUFFERED
              value: "1"
            
            # Volumes
            volumeMounts:
            - name: sync-code
              mountPath: /app
              readOnly: true
            
            # Recursos
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          
          # Volumes
          volumes:
          - name: sync-code
            configMap:
              name: fox-auditoria-sync-code
              defaultMode: 0755
          
          # Configurações do Pod
          # securityContext removido para permitir instalação de pacotes
          
          # Tolerâncias para execução em qualquer node
          tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"

