apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fox-auditoria
type: Opaque
data:
  # Base64 encoded MongoDB connection string
  # Para codificar: echo -n "sua-string-conexao" | base64
  # Substitua pela sua string de conexão MongoDB codificada em base64
  mongodb-uri: bW9uZ29kYitzcnY6Ly9kb2FkbWluOjV2azlhMDhOMnRYM2U2NFVAZm94ZGlnaXRhbC1lOGJmMDAyNC5tb25nby5vbmRpZ2l0YWxvY2Vhbi5jb20vZm94P2F1dGhTb3VyY2U9YWRtaW4mcmVwbGljYVNldD1mb3hkaWdpdGFs

